### ISSUE TITLE
reporter: github formatter

### ISSUE THREAD

**Issue by DonIsaac** [DonIsaac/zlint#150]
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-error-message

**Comment by BratishkaErik** [comment]
May want to check SARIF too:

https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning

https://github.com/microsoft/sarif-tutorials

**Comment by DonIsaac** [comment]
> May want to check SARIF too:
> 
> https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning
> 
> https://github.com/microsoft/sarif-tutorials

Looks interesting. How popular/well supported is this format?

**Comment by DonIsaac** [comment]
Also this feature has been implemented so I'm closing this issue
